### ISSUE TITLE
Source files are empty

### ISSUE THREAD

**Issue by Jeff-Birt** [pockemul/PockEmul_Issues#4]
Hello, I found PocketEmu when trying to find a ROM dump of the CE-150 plotter. I was hoping the source code might contain the ROM dumps. I found that both the ZIP and TAR just have a readme file in them.

**Comment by pockemul** [comment]
Hi.
PockEmul is not anymore open source and is available for Android on Google Play store.
https://play.google.com/store/apps/details?id=com.myrio.pockemul

You will find the CE-150 ROM file in attachment.

Best regards

[CE-150.zip](https://github.com/pockemul/PockEmul_Issues/files/5232327/CE-150.zip)

**Comment by Jeff-Birt** [comment]
Thank you! I was attempting to save the CE-150 ROM address area out of PocketEMU through virtual CE-150 interface but I could not find where the file was saved to.
