### ISSUE TITLE
In Keyboard Simulation (Sharp PC-1403) the '=' (ASCII 0x3D) is ignored

### ISSUE THREAD

**Issue by ffxx68** [pockemul/PockEmul_Issues#6]
Entering a string in the keyboard simulator including the '=' character (ASCII 0x3D), e.g. in PROGRAM mode on PC-1403:

50200 A=0:B=0:C=0:D=0:E=0:F=0:G=0:H=0:I=0:L=0

I get this on the emulated device:

50200:A0:B0:C0:D0:E0:F0:G0:H0:I0:L0

**Comment by pockemul** [comment]
Arg. The = sign is not correctly mapped !
Give me some minutes ...

**Comment by pockemul** [comment]
So the mapping of the = key is wrong.
Fortunately, there was a hidden way to customize mapping. We will use it to fix this issue.

In your user directory, there is a directory pockemul. In this directory are stored the config.ini files and all yours sessions.
Create a directory res/pc1401 in this pockemul directory and uncompress the file pc1403.map in this directory.
The full path of the file must be: C:/users/YourUsername/pockemul/res/pc1401/pc1403.map

Restart PockEmul, it should work.


[pc1403.zip](https://github.com/pockemul/PockEmul_Issues/files/8391385/pc1403.zip)

**Comment by pockemul** [comment]
The whole serie PC-14xx has this issue.
If you need to use one pocket of this serie other than the PC-1403, I will give you the patched files.
Or the v2.4.1 if you want to test it before the official release date :-)

**Comment by ffxx68** [comment]
Adding the file res/pc1401/pc1403.map and restarting didn't work.

**Comment by pockemul** [comment]
Strange, I just test with 2.3.0 on a fresh install and it works.
To see if the pockemul/res/pc1401/pc1403.map file is loaded you can check the list of keys in the keyboard Simulator
The "Equal" key should be replaced by "="
![image](https://user-images.githubusercontent.com/6992719/161243669-d01ebc83-6202-4c34-b7c7-b034a3303243.png)
![image](https://user-images.githubusercontent.com/6992719/161243934-3b956d9a-5948-41a1-836f-b7091747f3fd.png)

**Comment by ffxx68** [comment]
my list is different
![image](https://user-images.githubusercontent.com/659557/161244723-3e911901-d842-4001-a9ad-4e2d66178e28.png)

**Comment by ffxx68** [comment]
btw -  why the GUI font size is SO BIG? You need a huge windows to see it all

**Comment by pockemul** [comment]
ok.
The path is not correct.
It is not "Programmi/PockEmul".
There is a "pockemul" directory in your user directory: c:\users\username\pockemul (I don't know the label in italian)

**Comment by pockemul** [comment]
> btw - why the GUI font size is SO BIG? You need a huge windows to see it all

Yes, I agree. It comes from touch UI.
I will try to define a lower font size

**Comment by ffxx68** [comment]
Ok, it works now
