### ISSUE TITLE
Can't start Windows version - stays minimized

### ISSUE THREAD

**Issue by ffxx68** [pockemul/PockEmul_Issues#9]
![image](https://user-images.githubusercontent.com/659557/164446249-22631c56-cf90-4c16-b574-6fd588be72dc.png)
It was like this with previous version 2.3.0 as well. This is 2.4.1 and I hoped it would be solved with a new install, but it's not... 
I solved once after a complete uninstall and re-install... But that's not a solution obviously.

**Comment by pockemul** [comment]
What do you mean by "complete" uninstall ?
only uninstall PockEmul or uninstall + delete PockEmul directory in the "users" directory ?

**Comment by ffxx68** [comment]
uninstall PockEmul

**Comment by ffxx68** [comment]
Just a problem with Windows and double screen...
